"""Supplementary RQ3 state-space stress-boundary experiment."""

EXPERIMENT_ID = "EXP-S4-010_RQ3_STRESS_BOUNDARY"
FREEZE_STATUS = "FORMAL_PROTOCOL_FROZEN_PENDING_COMMIT_BOUND_AUTHORIZATION"
RAW_STATUS = "FORMAL_RAW_PENDING_MAC_REVIEW"
DERIVED_STATUS = "DERIVED_PENDING_MAC_REVIEW"

CONTRACT_RELATIVE = (
    "03_experiments/contracts/EXP-S4-010_RQ3_STRESS_BOUNDARY_FORMAL.json"
)
RAW_RELATIVE = "03_experiments/raw/EXP-S4-010_RQ3_STRESS_BOUNDARY"
DERIVED_RELATIVE = "03_experiments/derived/EXP-S4-010_RQ3_STRESS_BOUNDARY"
